### ISSUE TITLE
object不存在时cJSON_GetObjectItem返回结果错误

### ISSUE THREAD

**Issue by sigusr1** [RT-Thread-packages/cJSON#5]
1. 如下面的源码所示，如果待查找的节点不存在，返回结果非空

`cJSON *cJSON_GetObjectItem(cJSON *object,const char *string)	{cJSON *c=object->child; while (c && cJSON_strcasecmp(c->string,string)) c=c->next; return c;}`

2. 最好能注明下，这里的cJson时从哪里基于哪个版本fork出来的，方便使用者维护

**Comment by mysterywolf** [comment]
你好 官方仓库为： https://github.com/DaveGamble/cJSON  欢迎参与维护
